name: React CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# This tells GitHub to run every single npm command inside your subfolder
defaults:
  run:
    working-directory: ./habit-tracker-cicd

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Dependencies
      run: npm install

    - name: Run Linter
      run: npm run lint
      continue-on-error: true

    - name: Run Unit Tests
      run: npm run test

    - name: Build Application
      run: npm run build
